version: '3.1'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress-network

  php:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "php /usr/local/bin/wp-install.php && docker-php-entrypoint php-fpm"
    ports:
      - "9000:9000"
    env_file: .env
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - wordpress-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    depends_on:
      - php
    networks:
      - wordpress-network
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.nginx.rule=Host(`kaaz.app`)"
      - "traefik.http.routers.nginx.priority=10"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wordpress-network
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.kaaz.app`)"
      - "traefik.http.routers.phpmyadmin.priority=1"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"

volumes:
  db_data:

networks:
  wordpress-network:
    driver: bridge
  default:
    external:
      name: traefik_network
